"""Export data/past_questions.toml: one text fingerprint per FS-Quiz bank question, so the app can recognise a pasted
question without shipping any question text.

    uv run python scripts/export_past.py ../../../IFS-Tests/data/fsquiz/bank.json

Per question: id, the quizzes it appeared in ("FSG 2023"), the official answer only when it is a short number with a
unit (never prose), `fp` (sorted FNV-1a hashes of the word 3-grams, numbers masked) and `nums` (hashes of the numbers
in the text). The tokenizer and hashes must stay identical to src/past.rs.
"""

import base64
import json
import re
import struct
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parents[3] / "data" / "past_questions.toml"

TOKEN = re.compile(r"[A-Za-z]+|[0-9]+(?:[.,][0-9]+)*")
ANSWER = re.compile(r"^[-+]?\d+(?:[.,]\d+)?(?:\s*-\s*[-+]?\d+(?:[.,]\d+)?)?(?:\s*[^\d\s]\S{0,9})?$")
INVISIBLE = dict.fromkeys([0x200B, 0x200C, 0x200D, 0x2060, 0xFEFF])


def fnv1a(s: str) -> int:
    h = 0x811C9DC5
    for b in s.encode():
        h = ((h ^ b) * 0x01000193) & 0xFFFFFFFF
    return h


def canonical_number(tok: str) -> str:
    tok = tok.replace(",", ".")
    whole, _, frac = tok.partition(".")
    whole = whole.lstrip("0") or "0"
    frac = frac.rstrip("0")
    return f"{whole}.{frac}" if frac else whole


def fingerprint(text: str) -> tuple[list[int], list[int]]:
    words, nums = [], set()
    for tok in TOKEN.findall(text):
        if tok[0].isdigit():
            words.append("#")
            nums.add(fnv1a(canonical_number(tok)))
        else:
            words.append(tok.lower())
    if len(words) < 3:
        shingles = {fnv1a(" ".join(words))}
    else:
        shingles = {fnv1a(" ".join(words[i : i + 3])) for i in range(len(words) - 2)}
    return sorted(shingles), sorted(nums)


def b64(hashes: list[int]) -> str:
    return base64.b64encode(struct.pack(f"<{len(hashes)}I", *hashes)).decode().rstrip("=")


def numeric_answer(q: dict) -> str | None:
    correct = [a for a in q["answers"] if a["is_correct"]]
    if len(correct) != 1 or q["type"] == "multi-choice":
        return None
    text = correct[0]["text"].translate(INVISIBLE).replace("−", "-").replace("–", "-")
    text = " ".join(text.split())
    return text if ANSWER.match(text) else None


def quiz_labels(q: dict, quizzes: dict, events: dict) -> list[str]:
    labels = []
    for ref in q["quizzes"]:
        quiz = quizzes[ref["quiz_id"]]
        names = "/".join(events[e] for e in quiz["event_ids"]) or "FS-Quiz"
        labels.append((quiz["year"], f"{names} {quiz['year']} {quiz['class'].upper()}"))
    return [label for _, label in sorted(set(labels))]


def main(bank: Path) -> None:
    data = json.loads(bank.read_text())
    events = {e["event_id"]: e["short_name"] for e in data["events"]}
    quizzes = {z["quiz_id"]: z for z in data["quizzes"]}
    out = [
        "# Fingerprints of the FS-Quiz bank questions, generated by legacy/python/scripts/export_past.py (ODbL).",
        "# Hashes, ids and short numeric answers only: no question text can be read back from this file.",
        "# fp = base64 of sorted little-endian u32 FNV-1a hashes of word 3-grams (numbers masked), nums = same for the numbers.",
        "",
    ]
    rows = 0
    for q in sorted(data["questions"], key=lambda q: q["question_id"]):
        fp, nums = fingerprint(q["text"])
        out.append("[[q]]")
        out.append(f"id = {q['question_id']}")
        out.append(f"quizzes = {json.dumps(quiz_labels(q, quizzes, events), ensure_ascii=False)}")
        if (answer := numeric_answer(q)) is not None:
            out.append(f"answer = {json.dumps(answer, ensure_ascii=False)}")
        out.append(f'nums = "{b64(nums)}"')
        out.append(f'fp = "{b64(fp)}"')
        out.append("")
        rows += 1
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT} ({rows} questions, {OUT.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: export_past.py <bank.json>")
    main(Path(sys.argv[1]))
